---
title: "PM566 HW5"
author: "Jiqing Wu"
output: 
    html_document:
        toc: TRUE
        toc_float: TRUE
---
<br>

This is my PM566 HW5. 

<br>

<br>

## First Step
load files first

```{r setup, message=FALSE, echo=FALSE, warning=FALSE}
knitr::opts_chunk$set(include  = TRUE)
library(ggplot2)
library(tidyr)
library(data.table)
library(tidyverse)
library(leaflet)
library(dplyr)
library(dtplyr)
library(plotly)
library(knitr)
library(DT)
opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  eval=TRUE,
  echo = TRUE,
  fig.width = 7, 
  fig.align = 'center',
  fig.asp = 0.618,
  out.width = "700px")
```


```{r load-data}
load("/Users/jiqingwu/Desktop/566 Introduction to Health Data Science/midterm/Arrest2010.rda")
load("/Users/jiqingwu/Desktop/566 Introduction to Health Data Science/midterm/Arrest2019.rda")
```

<br>

## Second Step
These are my code for plots

```{r plot1, class.source="code-r-small"}
Arrest2019$TimeCode <- recode(Arrest2019$PartOfDay, "dawn"=1,"moring"=2,"afternoon"=3,"night"=4 )
fig1<-Arrest2019 %>% filter(Area.Name=="West LA") %>% filter(Age<25) %>%
plot_ly(x = ~Age, y = ~Arrest.Type, 
        color = ~Sex.Code, type = "scatter", mode = "markers", 
        size = ~TimeCode, sizes = c(10, 50), marker = list(sizemode='diameter', opacity=0.5),
        hoverinfo = 'text',
        text = ~paste( paste("Age: ", Age, sep=""), 
                       paste("Arrest Type: ", Arrest.Type, sep=""), 
                       paste("Time: ", PartOfDay, sep=""), 
                       paste("Sex: ", Sex.Code, sep=""), 
                       sep = "<br>"))
```


```{r plot2, class.source="code-r-small"}
g1 <- Arrest2019 %>% filter(Area.Name=="West LA") %>% 
  plot_ly(x = ~Age, type = "histogram", xbins = list(size = 1, end=30 ))
g2 <- Arrest2010 %>% filter(Area.Name=="West LA") %>% ggplot( aes(x=Age)) + geom_histogram(binwidth=1)
g2_plotly <- ggplotly(g2)
fig2<-subplot(g1, g2_plotly)
```


```{r plot3, class.source="code-r-small"}
ArrestTable <- Arrest2019 %>% filter(Area.Name=="West LA") %>% 
  select(Arrest.Date, Time, Arrest.Type, Age, Sex.Code)
fig3<-datatable(ArrestTable)
```

<br>

## Third Step
Here are my scatter plot, histogram and tables

```{r fig1}
fig1
```

```{r fig2}
fig2
```

```{r fig3}
fig3
```